CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
	id INTEGER AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(40) NOT NULL,
	devoured BOOLEAN NOT NULL,
	createdAt TIMESTAMP DEFAULT NOT NULL CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);